version: '3'

services:
  cmake_test:
    build: .
    image: denley/cmake:3.9.5
    working_dir: /opt/cmake
    entrypoint: /opt/cmake/docker-entrypoint.sh
    volumes:
      - ./main.cpp:/opt/cmake/main.cpp
      - ./CMakeLists.txt:/opt/cmake/CMakeLists.txt
      - ./docker-entrypoint.sh:/opt/cmake/docker-entrypoint.sh
